spring.application.name=Cinema-Ticket-Reservation-App

server.port = 3000

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Cinema Ticket Reservation DB;encrypt=true;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=Samy@2026

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true